apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - main
jobs:
  sam:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout
  build:
    needs: sam 
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"

