name: PR Dashboard Workflow

on:
  pull_request:
    branches:
      - main
      - devops

jobs:
  gather-dashboard-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Example: Generate a dashboard as an HTML file or image
        id: sample
        run: |
          echo "<html><body><h1>Dashboard Report</h1><p>Code coverage: 85%, Build time: 10 mins</p></body></html>" > dashboard.html

      # Upload the dashboard as an artifact
      - name: Upload Dashboard
        uses: actions/upload-artifact@v3
        with:
          name: dashboard
          path: dashboard.html

      # Post a link to the artifact in the PR
      - name: Comment with Dashboard Link
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Dashboard Report\n\nA dashboard was generated. You can download it [here](../actions/runs/${context.runId}).`
            })
