apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: MyWorkflow
on:
  pull_request:
    branches:
      - main
      - vim

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

  log-pr-details:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Log Pull Request Details
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Description: ${{ github.event.pull_request.body }}"
          echo "PR Source Branch: ${{ github.event.pull_request.head.ref }}"
          echo "PR Target Branch: ${{ github.event.pull_request.base.ref }}"
          echo "PR URL: ${{ github.event.pull_request.html_url }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"

  build:
    needs: log-pr-details
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: sample
        uses: actions/checkout@v2
        run: |
          chmod +x gradlew
          ./gradlew clean build

  security-scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Advanced Security Scan
        uses: github/codeql-action/init@v1
        with:
          languages: 'java'
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
