apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - main
jobs:
  sam:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout
  build:
    needs: sam 
    steps:
      - name: Build
        uses: docker://docker://openjdk:17-alpine
        shell: sh
        run: |
         ./ gradlew clean build

