apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:

  pull_request:
    branches:
      - devops
jobs:
  sam:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout
  build:
    needs: sam
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        shell: sh
        run: |
          chmod -R 777 .
          ./gradlew clean build
      - name: Scan with GitHub Advanced Security
        uses: cloudbees-io/github-security-sast-scan-code@v1
        with:
          token: ${{ secrets.GITHUB_SECRET }}
          language: LANGUAGE_JAVA
      - name: Scan with Find Security Bugs
        uses: cloudbees-io/findsecbugs-sast-scan-code@v1
        with:
          language: LANGUAGE_JAVA
